#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Cody Duong | artNcode
url: 'https://cody-duong.github.io'
#baseurl: '/artNcode' #change it according to your repository name
description: Currently under construction. Mostly useful though.

# Tracker
#analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
#host: 127.0.0.1
safe: false
